# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 559)
        MainWindow.setMinimumSize(QtCore.QSize(390, 559))
        MainWindow.setMaximumSize(QtCore.QSize(390, 559))
        MainWindow.setStyleSheet("background-color: rgb(118, 125, 157);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(70, 30, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.button_intro = QtWidgets.QPushButton(self.centralwidget)
        self.button_intro.setGeometry(QtCore.QRect(160, 330, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_intro.setFont(font)
        self.button_intro.setStyleSheet("border-top-color: rgb(0, 0, 0);\n"
"background-color: rgb(166, 169, 197);")
        self.button_intro.setObjectName("button_intro")
        self.label_question = QtWidgets.QLabel(self.centralwidget)
        self.label_question.setGeometry(QtCore.QRect(10, 80, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_question.setFont(font)
        self.label_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question.setWordWrap(True)
        self.label_question.setObjectName("label_question")
        self.list_moods = QtWidgets.QListWidget(self.centralwidget)
        self.list_moods.setGeometry(QtCore.QRect(70, 160, 256, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.list_moods.setFont(font)
        self.list_moods.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_moods.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.list_moods.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.list_moods.setObjectName("list_moods")
        self.label_rec = QtWidgets.QLabel(self.centralwidget)
        self.label_rec.setGeometry(QtCore.QRect(60, 290, 261, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_rec.setFont(font)
        self.label_rec.setText("")
        self.label_rec.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rec.setWordWrap(True)
        self.label_rec.setObjectName("label_rec")
        self.button_next = QtWidgets.QPushButton(self.centralwidget)
        self.button_next.setGeometry(QtCore.QRect(160, 440, 75, 23))
        self.button_next.setStyleSheet("background-color: rgb(166, 169, 197);")
        self.button_next.setObjectName("button_next")
        self.label_title.raise_()
        self.label_question.raise_()
        self.list_moods.raise_()
        self.button_intro.raise_()
        self.label_rec.raise_()
        self.button_next.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Song Recommender"))
        self.label_title.setText(_translate("MainWindow", "The Way We Feel"))
        self.button_intro.setText(_translate("MainWindow", "Begin"))
        self.label_question.setText(_translate("MainWindow", "Choose the emotion you are feeling now. Double click"))
        self.button_next.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
